import type { ClassLevel, Subject } from '@/types'

export interface TopicContent {
  id: string
  title: string
  description: string
  activities: string[]
  keyWords: string[]
  term: 1 | 2 | 3
  subject: Subject
  class: ClassLevel
  difficulty: 'foundation' | 'intermediate' | 'advanced'
}

export const SPROUT_2_CURRICULUM: TopicContent[] = [
  // ── LITERACY ──────────────────────────────────────────────
  {
    id: 'sp2-lit-t1',
    title: 'Jolly Phonics Set 1',
    description: 'Learn the sounds s, a, t, i, p, n',
    activities: [
      'Hear and recognise each sound',
      'Match sound to letter card',
      'Tap letter to hear Kòkò say the sound',
      'Trace the letter shape',
    ],
    keyWords: ['s', 'a', 't', 'i', 'p', 'n'],
    term: 1,
    subject: 'literacy',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
  {
    id: 'sp2-lit-t2',
    title: 'Jolly Phonics Set 2',
    description: 'Learn the sounds ck, e, h, r, m, d',
    activities: [
      'Hear and recognise each sound',
      'Match sound to letter card',
      'Tap letter to hear Kòkò say the sound',
      'Trace the letter shape',
    ],
    keyWords: ['ck', 'e', 'h', 'r', 'm', 'd'],
    term: 2,
    subject: 'literacy',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
  {
    id: 'sp2-lit-t3',
    title: 'Jolly Phonics Set 3',
    description: 'Learn the sounds g, o, u, l, f, b and simple blending',
    activities: [
      'Hear and recognise each sound',
      'Blend two sounds together',
      'Match word to image',
    ],
    keyWords: ['g', 'o', 'u', 'l', 'f', 'b'],
    term: 3,
    subject: 'literacy',
    class: 'sprout_2',
    difficulty: 'foundation',
  },

  // ── LETTER NAME ───────────────────────────────────────────
  {
    id: 'sp2-ln-t1',
    title: 'Days of the Week',
    description: 'Recognise and say the days of the week',
    activities: [
      'Say each day of the week',
      'Point to today on the calendar',
      'Arrange days in order',
    ],
    keyWords: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    term: 1,
    subject: 'letter_name',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
  {
    id: 'sp2-ln-t2',
    title: 'Parts of the Body',
    description: 'Name and point to body parts',
    activities: [
      'Point to body part when named',
      'Say the name of each body part',
      'Match body part to image',
    ],
    keyWords: ['head', 'eyes', 'nose', 'mouth', 'ears', 'hands', 'feet', 'tummy'],
    term: 2,
    subject: 'letter_name',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
  {
    id: 'sp2-ln-t3',
    title: 'Simple 3-Letter Words',
    description: 'Spell simple CVC words',
    activities: [
      'Tap letters to spell the word',
      'Match word to picture',
      'Identify missing letter in a word',
    ],
    keyWords: ['bag', 'cat', 'dog', 'hat', 'mat', 'pen', 'cup', 'bus'],
    term: 3,
    subject: 'letter_name',
    class: 'sprout_2',
    difficulty: 'foundation',
  },

  // ── NUMERACY ──────────────────────────────────────────────
  {
    id: 'sp2-num-t1',
    title: 'Count 1 to 20',
    description: 'Count objects and recognise numbers 1 to 20',
    activities: [
      'Count objects on screen',
      'Tap the correct number',
      'Write numbers 1 to 20',
    ],
    keyWords: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20'],
    term: 1,
    subject: 'numeracy',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
  {
    id: 'sp2-num-t2',
    title: 'Count 1 to 50 and Simple Addition',
    description: 'Count to 50 and add small numbers',
    activities: [
      'Count objects up to 50',
      'Simple addition: 1+1, 2+1, 3+2',
      'Count on fingers',
    ],
    keyWords: ['addition', 'plus', 'equals', 'count', '50'],
    term: 2,
    subject: 'numeracy',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
  {
    id: 'sp2-num-t3',
    title: 'Count 1 to 100 and Addition up to 10',
    description: 'Count to 100 and add numbers up to 10',
    activities: [
      'Count to 100',
      'Addition up to 10',
      'Number matching games',
    ],
    keyWords: ['100', 'addition', 'number line'],
    term: 3,
    subject: 'numeracy',
    class: 'sprout_2',
    difficulty: 'foundation',
  },

  // ── SCIENCE ───────────────────────────────────────────────
  {
    id: 'sp2-sci-t1',
    title: 'The Stem',
    description: 'What is a stem? What does it look like?',
    activities: [
      'Identify the stem on a plant image',
      'Define what a stem does',
      'Match stem to plant',
    ],
    keyWords: ['stem', 'plant', 'support', 'water', 'upright'],
    term: 1,
    subject: 'science',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
  {
    id: 'sp2-sci-t2',
    title: 'The Leaf',
    description: 'What is a leaf? What does it look like? Types of leaves',
    activities: [
      'Identify different leaf shapes',
      'Say what a leaf does',
      'Match leaf to plant',
    ],
    keyWords: ['leaf', 'green', 'shape', 'veins', 'broad', 'narrow'],
    term: 2,
    subject: 'science',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
  {
    id: 'sp2-sci-t3',
    title: 'Soil',
    description: 'Define soil. Types of soil. Uses of soil.',
    activities: [
      'Identify clay soil, loamy soil, sandy soil',
      'What can we do with soil?',
      'Match soil type to use',
    ],
    keyWords: ['soil', 'clay', 'loamy', 'sandy', 'farming', 'building'],
    term: 3,
    subject: 'science',
    class: 'sprout_2',
    difficulty: 'foundation',
  },

  // ── ZOOLOGY & BOTANY ──────────────────────────────────────
  {
    id: 'sp2-zoo-t1',
    title: 'Domestic Animals',
    description: 'Animals we keep at home',
    activities: [
      'Name domestic animals',
      'Tap animal to hear its sound',
      'Match animal to home',
    ],
    keyWords: ['dog', 'cat', 'cow', 'goat', 'chicken', 'sheep'],
    term: 1,
    subject: 'zoology_botany',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
  {
    id: 'sp2-zoo-t2',
    title: 'Farm Animals vs Wild Animals',
    description: 'Where do animals live?',
    activities: [
      'Sort animals into farm or wild',
      'Name each animal',
      'Match animal to habitat',
    ],
    keyWords: ['farm', 'wild', 'forest', 'lion', 'elephant', 'cow', 'pig'],
    term: 2,
    subject: 'zoology_botany',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
  {
    id: 'sp2-zoo-t3',
    title: 'Living and Non-Living Things',
    description: 'What is alive? What is not alive?',
    activities: [
      'Sort items into living and non-living',
      'Explain why something is living',
      'Identify living things around us',
    ],
    keyWords: ['living', 'non-living', 'breathe', 'grow', 'move', 'eat'],
    term: 3,
    subject: 'zoology_botany',
    class: 'sprout_2',
    difficulty: 'foundation',
  },

  // ── HEALTH HABITS ─────────────────────────────────────────
  {
    id: 'sp2-hh-t1',
    title: 'Washing Hands and Brushing Teeth',
    description: 'How to keep hands and teeth clean',
    activities: [
      'Steps to wash hands correctly',
      'How to brush teeth',
      'When should we wash our hands?',
    ],
    keyWords: ['wash', 'hands', 'teeth', 'brush', 'soap', 'clean'],
    term: 1,
    subject: 'health_habits',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
  {
    id: 'sp2-hh-t2',
    title: 'Taking Care of Nails and Hair',
    description: 'Personal grooming basics',
    activities: [
      'Why do we cut our nails?',
      'How to comb hair',
      'Match grooming tool to body part',
    ],
    keyWords: ['nails', 'hair', 'comb', 'cut', 'clean', 'neat'],
    term: 2,
    subject: 'health_habits',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
  {
    id: 'sp2-hh-t3',
    title: 'Wearing Clothes and Keeping Clean',
    description: 'How to dress neatly and stay clean',
    activities: [
      'Which clothes do we wear when?',
      'How to fold and arrange clothes',
      'Why is cleanliness important?',
    ],
    keyWords: ['clothes', 'neat', 'uniform', 'clean', 'dress', 'sharp'],
    term: 3,
    subject: 'health_habits',
    class: 'sprout_2',
    difficulty: 'foundation',
  },

  // ── SOCIAL HABITS ─────────────────────────────────────────
  {
    id: 'sp2-sh-t1',
    title: 'How to Greet',
    description: 'Greet teachers and friends politely',
    activities: [
      'Good morning / Good afternoon practice',
      'How to greet an elder',
      'Role play greetings',
    ],
    keyWords: ['greet', 'good morning', 'please', 'thank you', 'welcome'],
    term: 1,
    subject: 'social_habits',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
  {
    id: 'sp2-sh-t2',
    title: 'Being Kind to Friends',
    description: 'How to treat classmates with kindness',
    activities: [
      'Share your things',
      'Do not push or shout',
      'Help a friend who is sad',
    ],
    keyWords: ['kind', 'share', 'gentle', 'friend', 'help', 'care'],
    term: 2,
    subject: 'social_habits',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
  {
    id: 'sp2-sh-t3',
    title: 'Classroom Rules',
    description: 'How to behave in class',
    activities: [
      'Listen when teacher is talking',
      'Raise your hand before speaking',
      'Keep your desk tidy',
    ],
    keyWords: ['listen', 'quiet', 'hand up', 'tidy', 'respect', 'rules'],
    term: 3,
    subject: 'social_habits',
    class: 'sprout_2',
    difficulty: 'foundation',
  },

  // ── COLOURS & SHAPES ──────────────────────────────────────
  {
    id: 'sp2-cs-t1',
    title: 'Primary Colours',
    description: 'Red, blue and yellow — the three primary colours',
    activities: [
      'Identify red, blue and yellow',
      'Find these colours in the classroom',
      'Colour a picture using primary colours',
    ],
    keyWords: ['red', 'blue', 'yellow', 'primary', 'colour'],
    term: 1,
    subject: 'colours_shapes',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
  {
    id: 'sp2-cs-t2',
    title: 'Secondary Colours and Basic Shapes',
    description: 'Green, orange, purple and circle, square, triangle',
    activities: [
      'What colours mix to make green?',
      'Name and draw circle, square, triangle',
      'Find shapes in the classroom',
    ],
    keyWords: ['green', 'orange', 'purple', 'circle', 'square', 'triangle'],
    term: 2,
    subject: 'colours_shapes',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
  {
    id: 'sp2-cs-t3',
    title: 'All Colours and More Shapes',
    description: 'Full colour set and rectangle, oval, diamond',
    activities: [
      'Name all colours',
      'Draw and name rectangle, oval, diamond',
      'Sort objects by colour and shape',
    ],
    keyWords: ['rectangle', 'oval', 'diamond', 'pink', 'brown', 'black', 'white'],
    term: 3,
    subject: 'colours_shapes',
    class: 'sprout_2',
    difficulty: 'foundation',
  },

  // ── FRENCH ────────────────────────────────────────────────
  {
    id: 'sp2-fr-t1',
    title: 'Basic French Greetings',
    description: 'Bonjour, Au revoir, numbers 1–5',
    activities: [
      'Say Bonjour and Au revoir',
      'Count 1–5 in French',
      'Tap number to hear French pronunciation',
    ],
    keyWords: ['bonjour', 'au revoir', 'un', 'deux', 'trois', 'quatre', 'cinq'],
    term: 1,
    subject: 'french',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
  {
    id: 'sp2-fr-t2',
    title: 'Body Parts in French',
    description: 'Name body parts in French',
    activities: [
      'Tap body part to hear French name',
      'Match French word to body part',
      'Simple French body song',
    ],
    keyWords: ['tête', 'yeux', 'nez', 'bouche', 'mains', 'pieds'],
    term: 2,
    subject: 'french',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
  {
    id: 'sp2-fr-t3',
    title: 'Colours in French',
    description: 'Name colours in French',
    activities: [
      'Tap colour to hear French name',
      'Match colour to French word',
      'Simple French colour song',
    ],
    keyWords: ['rouge', 'bleu', 'jaune', 'vert', 'orange', 'violet'],
    term: 3,
    subject: 'french',
    class: 'sprout_2',
    difficulty: 'foundation',
  },
]

// ════════════════════════════════════════════════════════════
// SPROUT 3 CURRICULUM
// ════════════════════════════════════════════════════════════

export const SPROUT_3_CURRICULUM: TopicContent[] = [
  // ── LITERACY ──────────────────────────────────────────────
  {
    id: 'sp3-lit-t1',
    title: 'Jolly Phonics Set 4 — Blending',
    description: 'Learn sounds ai, j, oa, ie, ee, or and blend them into words',
    activities: [
      'Hear and recognise each sound',
      'Blend two sounds: r-ai-n = rain',
      'Match blended word to image',
    ],
    keyWords: ['ai', 'j', 'oa', 'ie', 'ee', 'or', 'rain', 'road', 'feet'],
    term: 1,
    subject: 'literacy',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-lit-t2',
    title: 'Jolly Phonics Set 5 — More Blending',
    description: 'Learn sounds z, w, ng, v and blend into words',
    activities: [
      'Sound recognition',
      'Blend sounds into 3-letter words',
      'Read simple words aloud',
    ],
    keyWords: ['z', 'w', 'ng', 'v', 'wing', 'vest', 'zoo'],
    term: 2,
    subject: 'literacy',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-lit-t3',
    title: 'Jolly Phonics Sets 6 & 7 — Simple Sentences',
    description: 'Read and understand simple sentences',
    activities: [
      'Read a 3-word sentence',
      'Match sentence to picture',
      'Fill in missing word',
    ],
    keyWords: ['sentence', 'read', 'word', 'picture', 'qu', 'ou', 'ch', 'sh', 'th'],
    term: 3,
    subject: 'literacy',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },

  // ── LETTER NAME ───────────────────────────────────────────
  {
    id: 'sp3-ln-t1',
    title: 'Spell Days of the Week',
    description: 'Spell M-O-N-D-A-Y and all days of the week',
    activities: [
      'Tap letters to spell each day',
      'Arrange scrambled letters',
      'Write each day from memory',
    ],
    keyWords: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    term: 1,
    subject: 'letter_name',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-ln-t2',
    title: 'Spell Parts of the Body',
    description: 'Spell E-Y-E, N-O-S-E and other body parts',
    activities: [
      'Tap letters to spell body part',
      'Match spelling to body part image',
      'Write body part names',
    ],
    keyWords: ['EYE', 'NOSE', 'HAND', 'FOOT', 'HEAD', 'BACK', 'NECK'],
    term: 2,
    subject: 'letter_name',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-ln-t3',
    title: 'Spell Colours and Shapes',
    description: 'Spell colour and shape names correctly',
    activities: [
      'Tap letters to spell RED, BLUE, GREEN',
      'Spell CIRCLE, SQUARE, TRIANGLE',
      'Identify misspelled word',
    ],
    keyWords: ['RED', 'BLUE', 'GREEN', 'CIRCLE', 'SQUARE', 'TRIANGLE'],
    term: 3,
    subject: 'letter_name',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },

  // ── NUMERACY ──────────────────────────────────────────────
  {
    id: 'sp3-num-t1',
    title: 'Count 1 to 100 and Addition up to 20',
    description: 'Count fluently to 100 and add numbers up to 20',
    activities: [
      'Count objects up to 100',
      'Addition: 8+7, 10+5',
      'Number line addition',
    ],
    keyWords: ['100', 'addition', 'sum', 'plus', 'equals'],
    term: 1,
    subject: 'numeracy',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-num-t2',
    title: 'Subtraction Intro and Count to 200',
    description: 'Introduce subtraction and count up to 200',
    activities: [
      'Count to 200',
      'Simple subtraction: 5-2=3, 8-4=4',
      'Subtraction using objects',
    ],
    keyWords: ['200', 'subtract', 'minus', 'take away', 'less'],
    term: 2,
    subject: 'numeracy',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-num-t3',
    title: 'Addition and Subtraction up to 50',
    description: 'Add and subtract numbers up to 50',
    activities: [
      'Addition up to 50',
      'Subtraction up to 50',
      'Word problems: Tayo had 20 mangoes...',
    ],
    keyWords: ['50', 'add', 'subtract', 'word problem', 'total'],
    term: 3,
    subject: 'numeracy',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },

  // ── SCIENCE ───────────────────────────────────────────────
  {
    id: 'sp3-sci-t1',
    title: 'Soil in Depth',
    description: 'Clay soil, loamy soil, sandy soil — properties and uses',
    activities: [
      'Identify the 3 types of soil',
      'Properties of each soil type',
      'What crops grow in each soil?',
    ],
    keyWords: ['clay soil', 'loamy soil', 'sandy soil', 'fertile', 'texture', 'farming'],
    term: 1,
    subject: 'science',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-sci-t2',
    title: 'Leaf in Depth',
    description: 'Photosynthesis introduction and types of leaves',
    activities: [
      'Parts of a leaf',
      'What does a leaf do for the plant?',
      'Types of leaves — broad, narrow, compound',
    ],
    keyWords: ['photosynthesis', 'sunlight', 'broad leaf', 'narrow leaf', 'veins', 'chlorophyll'],
    term: 2,
    subject: 'science',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-sci-t3',
    title: 'Stem in Depth',
    description: 'Functions and types of stems',
    activities: [
      'What does a stem do?',
      'Types of stems — woody and herbaceous',
      'Identify stem in plant diagram',
    ],
    keyWords: ['woody stem', 'herbaceous', 'support', 'transport', 'water', 'nutrients'],
    term: 3,
    subject: 'science',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },

  // ── ZOOLOGY & BOTANY ──────────────────────────────────────
  {
    id: 'sp3-zoo-t1',
    title: 'Birds',
    description: 'What birds look like and types of birds',
    activities: [
      'Identify common birds',
      'What do birds have that other animals don\'t?',
      'Match bird to its egg',
    ],
    keyWords: ['bird', 'feathers', 'beak', 'wings', 'eagle', 'parrot', 'chicken', 'pigeon'],
    term: 1,
    subject: 'zoology_botany',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-zoo-t2',
    title: 'Animals in Depth',
    description: 'Features of cow, goat, chicken in detail',
    activities: [
      'Describe features of each animal',
      'What do these animals give us?',
      'Match animal to its product (cow → milk)',
    ],
    keyWords: ['cow', 'milk', 'goat', 'cheese', 'chicken', 'egg', 'features', 'product'],
    term: 2,
    subject: 'zoology_botany',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-zoo-t3',
    title: 'Living vs Non-Living — Detailed',
    description: 'Classify and explain why things are living or non-living',
    activities: [
      'Sort 20 items into living and non-living',
      'Explain your sorting with a reason',
      'Identify the 5 signs of life',
    ],
    keyWords: ['breathe', 'grow', 'reproduce', 'respond', 'feed', 'move', 'classification'],
    term: 3,
    subject: 'zoology_botany',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },

  // ── SOCIAL HABITS ─────────────────────────────────────────
  {
    id: 'sp3-sh-t1',
    title: 'Respecting Elders',
    description: 'How to show respect to adults and teachers',
    activities: [
      'How do we greet an elder in Nigeria?',
      'Why do we respect elders?',
      'Role play respectful behaviour',
    ],
    keyWords: ['respect', 'elder', 'bow', 'greet', 'obey', 'polite'],
    term: 1,
    subject: 'social_habits',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-sh-t2',
    title: 'Sharing in Class',
    description: 'Why sharing is important and how to do it',
    activities: [
      'Share crayons with a friend activity',
      'Story: Tayo and the last mango',
      'When is sharing hard? How do we try anyway?',
    ],
    keyWords: ['share', 'generous', 'fair', 'together', 'enough for everyone'],
    term: 2,
    subject: 'social_habits',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-sh-t3',
    title: 'Community Helpers',
    description: 'People who help us in the community',
    activities: [
      'Name community helpers: teacher, doctor, driver, farmer, trader',
      'What does each helper do?',
      'Match helper to their tool',
    ],
    keyWords: ['teacher', 'doctor', 'driver', 'farmer', 'trader', 'police', 'community'],
    term: 3,
    subject: 'social_habits',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },

  // ── COLOURS & SHAPES ──────────────────────────────────────
  {
    id: 'sp3-cs-t1',
    title: 'All Shapes Including 3D',
    description: '2D and 3D shapes — sphere, cube, cylinder',
    activities: [
      'Name all 2D shapes',
      'Identify sphere, cube, cylinder in real life',
      'Match 3D shape to real object',
    ],
    keyWords: ['sphere', 'cube', 'cylinder', 'cone', '3D', 'solid shape'],
    term: 1,
    subject: 'colours_shapes',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-cs-t2',
    title: 'Mixing Colours',
    description: 'What happens when you mix colours?',
    activities: [
      'Red + Blue = Purple',
      'Blue + Yellow = Green',
      'Red + Yellow = Orange',
      'Colour mixing matching game',
    ],
    keyWords: ['mix', 'combine', 'primary', 'secondary', 'result', 'purple', 'orange', 'green'],
    term: 2,
    subject: 'colours_shapes',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-cs-t3',
    title: 'Patterns',
    description: 'Identify, draw and complete patterns',
    activities: [
      'What comes next in this pattern?',
      'Draw your own repeating pattern',
      'Colour pattern using two colours',
    ],
    keyWords: ['pattern', 'repeat', 'sequence', 'next', 'alternating'],
    term: 3,
    subject: 'colours_shapes',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },

  // ── FRENCH ────────────────────────────────────────────────
  {
    id: 'sp3-fr-t1',
    title: 'French Alphabet A–F',
    description: 'Learn the first 6 letters of the French alphabet with African words',
    activities: [
      'Tap letter to hear French pronunciation',
      'A — Ananas, B — Baobab, C — Caïman',
      'Match French letter to African word',
    ],
    keyWords: ['A', 'B', 'C', 'D', 'E', 'F', 'Ananas', 'Baobab', 'Caïman', 'Dakar', 'Éléphant', 'Fleuve'],
    term: 1,
    subject: 'french',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-fr-t2',
    title: 'Numbers 1–10 in French',
    description: 'Count to 10 in French',
    activities: [
      'Tap number to hear French name',
      'Count objects in French',
      'Un, deux, trois... song',
    ],
    keyWords: ['un', 'deux', 'trois', 'quatre', 'cinq', 'six', 'sept', 'huit', 'neuf', 'dix'],
    term: 2,
    subject: 'french',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-fr-t3',
    title: 'Simple French Sentences',
    description: 'Say and understand basic French sentences',
    activities: [
      'Je m\'appelle Àmì — My name is Àmì',
      'J\'ai cinq ans — I am five years old',
      'Match French sentence to meaning',
    ],
    keyWords: ['Je m\'appelle', 'J\'ai', 'ans', 'bonjour', 'comment tu t\'appelles?'],
    term: 3,
    subject: 'french',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },

  // ── HEALTH HABITS ─────────────────────────────────────────
  {
    id: 'sp3-hh-t1',
    title: 'Personal Hygiene Routine',
    description: 'Morning and night hygiene routines',
    activities: [
      'Arrange morning routine in order',
      'What do we do before bed?',
      'Match hygiene activity to time of day',
    ],
    keyWords: ['morning', 'night', 'routine', 'bath', 'brush', 'wash', 'sleep'],
    term: 1,
    subject: 'health_habits',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-hh-t2',
    title: 'Dental Hygiene',
    description: 'How to brush teeth properly',
    activities: [
      'Steps to brush teeth correctly',
      'How many times a day?',
      'What happens if we don\'t brush?',
    ],
    keyWords: ['teeth', 'brush', 'toothpaste', 'twice', 'cavity', 'dentist', 'healthy'],
    term: 2,
    subject: 'health_habits',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-hh-t3',
    title: 'Healthy Eating',
    description: 'Fruits and vegetables vs junk food',
    activities: [
      'Sort foods into healthy and unhealthy',
      'Name 5 fruits and 5 vegetables',
      'Why is junk food bad for us?',
    ],
    keyWords: ['fruits', 'vegetables', 'junk food', 'healthy', 'body', 'strong', 'sick'],
    term: 3,
    subject: 'health_habits',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },

  // ── SEASONAL CREATIVITY ───────────────────────────────────
  {
    id: 'sp3-sc-t1',
    title: 'Words and Opposites',
    description: 'Understand and use opposite words',
    activities: [
      'Match opposite pairs: big/small, hot/cold, day/night',
      'Fill in the opposite word',
      'Draw something big and something small',
    ],
    keyWords: ['big', 'small', 'hot', 'cold', 'day', 'night', 'fast', 'slow', 'up', 'down'],
    term: 1,
    subject: 'seasonal_creativity',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-sc-t2',
    title: 'Creative Writing Introduction',
    description: 'Describe what you see in a picture',
    activities: [
      'Look at a picture and say 2 things you see',
      'Complete the sentence: I can see a...',
      'Draw and describe your own picture',
    ],
    keyWords: ['describe', 'see', 'picture', 'sentence', 'I can see', 'write'],
    term: 2,
    subject: 'seasonal_creativity',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-sc-t3',
    title: 'Simple Storytelling',
    description: 'Tell a 2-sentence story about a picture',
    activities: [
      'Look at a scene and tell what is happening',
      'Beginning and end of a story',
      'Story about Àmì and Kòkò',
    ],
    keyWords: ['story', 'beginning', 'end', 'character', 'happen', 'tell', 'picture'],
    term: 3,
    subject: 'seasonal_creativity',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },

  // ── MUSIC & ARTS ──────────────────────────────────────────
  {
    id: 'sp3-ma-t1',
    title: 'Percussion Rhythms',
    description: 'Clap, tap and stomp to simple rhythms',
    activities: [
      'Clap along to a rhythm',
      'Copy the rhythm pattern',
      'Create your own clapping rhythm',
    ],
    keyWords: ['rhythm', 'clap', 'tap', 'stomp', 'beat', 'music', 'pattern'],
    term: 1,
    subject: 'music_arts',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-ma-t2',
    title: 'Drawing Animals',
    description: 'Draw animals from basic shapes',
    activities: [
      'Draw a cat using circles and triangles',
      'Draw a fish using oval and triangle',
      'Colour your animal drawing',
    ],
    keyWords: ['draw', 'animal', 'shape', 'circle', 'oval', 'triangle', 'colour'],
    term: 2,
    subject: 'music_arts',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-ma-t3',
    title: 'Painting Activities',
    description: 'Paint with fingers and brushes',
    activities: [
      'Finger painting patterns',
      'Brush painting simple scenes',
      'Mix paints to make new colours',
    ],
    keyWords: ['paint', 'brush', 'finger', 'colour', 'mix', 'scene', 'art'],
    term: 3,
    subject: 'music_arts',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },

  // ── PRACTICAL LIFE ────────────────────────────────────────
  {
    id: 'sp3-pl-t1',
    title: 'Setting the Table',
    description: 'How to set a table correctly',
    activities: [
      'Name items on a table: plate, cup, spoon, fork',
      'Arrange table setting in correct order',
      'Why do we set the table?',
    ],
    keyWords: ['plate', 'cup', 'spoon', 'fork', 'table', 'arrange', 'meal'],
    term: 1,
    subject: 'practical_life',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-pl-t2',
    title: 'Pouring Without Spilling',
    description: 'How to pour water carefully',
    activities: [
      'Steps to pour water without spilling',
      'Why is it important to be careful?',
      'Practice activity: pour from one cup to another',
    ],
    keyWords: ['pour', 'careful', 'steady', 'spill', 'water', 'cup', 'patient'],
    term: 2,
    subject: 'practical_life',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
  {
    id: 'sp3-pl-t3',
    title: 'Classroom Responsibilities',
    description: 'How to sweep and keep the classroom tidy',
    activities: [
      'How to sweep correctly',
      'Arrange your desk before leaving',
      'Pick up litter — why it matters',
    ],
    keyWords: ['sweep', 'tidy', 'responsibility', 'clean', 'classroom', 'litter', 'arrange'],
    term: 3,
    subject: 'practical_life',
    class: 'sprout_3',
    difficulty: 'intermediate',
  },
]
