"use client";

/**
 * TracingCanvas — guided letter tracing with waypoint validation.
 *
 * How it works:
 * - Each letter has a set of waypoints defining the correct stroke path
 * - As the child draws, we check if their finger passes near each waypoint IN ORDER
 * - Progress bar fills as waypoints are hit
 * - Only marks complete when ≥ 80% of waypoints are hit in sequence
 * - Ghost letter shown as guide; hit waypoints glow green
 */
import { useRef, useEffect, useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";

// ─── Waypoint definitions ─────────────────────────────────────────────────────
// Coordinates are in a 0–100 space, scaled to canvas size at render time.
// Each array is one stroke. Multiple strokes per letter are supported.
// Generated by tracing the natural path of each letter.

type Point = [number, number];
type Stroke = Point[];

const LETTER_PATHS: Record<string, Stroke[]> = {
  A: [
    [[50,10],[35,35],[20,60],[10,85]], // left leg down
    [[50,10],[65,35],[80,60],[90,85]], // right leg down
    [[30,58],[50,58],[70,58]],          // crossbar
  ],
  B: [
    [[20,10],[20,30],[20,55],[20,80],[20,90]], // vertical
    [[20,10],[40,10],[55,15],[60,25],[55,35],[40,40],[20,40]], // top bump
    [[20,40],[42,40],[58,45],[65,57],[58,70],[42,75],[20,75],[20,90]], // bottom bump
  ],
  C: [
    [[75,20],[60,10],[45,10],[30,15],[18,28],[12,45],[12,55],[18,72],[30,82],[45,88],[60,88],[75,80]],
  ],
  D: [
    [[20,10],[20,35],[20,55],[20,80],[20,90]], // vertical
    [[20,10],[40,10],[58,18],[68,32],[72,50],[68,68],[58,82],[40,90],[20,90]], // curve
  ],
  E: [
    [[75,10],[50,10],[25,10],[20,10]], // top
    [[20,10],[20,35],[20,55],[20,80],[20,90]], // vertical
    [[20,50],[40,50],[58,50]], // middle
    [[20,90],[45,90],[70,90]], // bottom
  ],
  F: [
    [[20,10],[20,35],[20,55],[20,80],[20,90]], // vertical
    [[20,10],[45,10],[70,10]], // top
    [[20,48],[42,48],[62,48]], // middle
  ],
  G: [
    [[75,20],[60,10],[45,10],[30,15],[18,28],[12,45],[12,55],[18,72],[30,82],[45,88],[60,88],[75,80],[75,65],[75,55],[55,55]],
  ],
  H: [
    [[20,10],[20,35],[20,55],[20,80],[20,90]], // left
    [[80,10],[80,35],[80,55],[80,80],[80,90]], // right
    [[20,50],[50,50],[80,50]], // crossbar
  ],
  I: [
    [[35,10],[50,10],[65,10]], // top serif
    [[50,10],[50,35],[50,55],[50,80],[50,90]], // vertical
    [[35,90],[50,90],[65,90]], // bottom serif
  ],
  J: [
    [[35,10],[50,10],[65,10]], // top
    [[50,10],[50,35],[50,55],[50,75],[45,85],[35,90],[25,88],[18,80],[18,70]],
  ],
  K: [
    [[20,10],[20,35],[20,55],[20,80],[20,90]], // vertical
    [[75,10],[55,30],[40,45],[20,50]], // upper diagonal in
    [[20,50],[40,60],[55,72],[75,90]], // lower diagonal out
  ],
  L: [
    [[20,10],[20,35],[20,55],[20,80],[20,90]], // vertical
    [[20,90],[45,90],[70,90]], // base
  ],
  M: [
    [[15,90],[15,60],[15,35],[15,10]], // left up
    [[15,10],[30,35],[50,60],[70,35],[85,10]], // peaks
    [[85,10],[85,35],[85,60],[85,90]], // right down
  ],
  N: [
    [[20,90],[20,60],[20,35],[20,10]], // left up
    [[20,10],[50,50],[80,90]], // diagonal
    [[80,90],[80,60],[80,35],[80,10]], // right up
  ],
  O: [
    [[50,10],[65,12],[78,22],[85,38],[85,50],[85,62],[78,78],[65,88],[50,90],[35,88],[22,78],[15,62],[15,50],[15,38],[22,22],[35,12],[50,10]],
  ],
  P: [
    [[20,10],[20,35],[20,55],[20,80],[20,90]], // vertical
    [[20,10],[40,10],[58,15],[65,25],[62,38],[55,45],[40,48],[20,48]], // bump
  ],
  Q: [
    [[50,10],[65,12],[78,22],[85,38],[85,50],[85,62],[78,78],[65,88],[50,90],[35,88],[22,78],[15,62],[15,50],[15,38],[22,22],[35,12],[50,10]],
    [[60,70],[75,88]], // tail
  ],
  R: [
    [[20,10],[20,35],[20,55],[20,80],[20,90]], // vertical
    [[20,10],[40,10],[58,15],[65,25],[62,38],[55,45],[40,48],[20,48]], // bump
    [[40,48],[55,62],[70,78],[80,90]], // leg
  ],
  S: [
    [[75,18],[62,10],[48,10],[35,15],[25,25],[25,38],[35,48],[50,52],[65,58],[75,68],[75,80],[65,88],[50,90],[35,88],[22,80]],
  ],
  T: [
    [[15,10],[35,10],[50,10],[65,10],[85,10]], // top
    [[50,10],[50,35],[50,55],[50,80],[50,90]], // vertical
  ],
  U: [
    [[20,10],[20,35],[20,55],[20,70],[25,82],[35,90],[50,92],[65,90],[75,82],[80,70],[80,55],[80,35],[80,10]],
  ],
  V: [
    [[15,10],[35,40],[50,75],[65,40],[85,10]],
  ],
  W: [
    [[10,10],[25,60],[40,35],[50,60],[60,35],[75,60],[90,10]],
  ],
  X: [
    [[20,10],[38,32],[50,50],[62,68],[80,90]], // top-left to bottom-right
    [[80,10],[62,32],[50,50],[38,68],[20,90]], // top-right to bottom-left
  ],
  Y: [
    [[20,10],[35,30],[50,50]], // left arm
    [[80,10],[65,30],[50,50]], // right arm
    [[50,50],[50,70],[50,90]], // stem
  ],
  Z: [
    [[15,10],[45,10],[75,10],[85,10]], // top
    [[85,10],[65,35],[50,50],[35,65],[15,90]], // diagonal
    [[15,90],[45,90],[75,90],[85,90]], // bottom
  ],
};

// Lowercase paths — simplified versions
const LOWER_PATHS: Record<string, Stroke[]> = {
  a: [[[65,35],[55,25],[42,25],[30,32],[25,45],[25,55],[30,68],[42,75],[55,75],[65,68],[65,55],[65,35],[65,55],[65,75],[65,85]]],
  b: [[[25,10],[25,35],[25,55],[25,75],[25,88]], [[25,55],[35,45],[48,42],[60,45],[68,55],[68,65],[60,75],[48,78],[35,75],[25,65]]],
  c: [[[68,38],[58,28],[45,25],[32,30],[22,42],[20,55],[22,68],[32,78],[45,82],[58,80],[68,72]]],
  d: [[[75,10],[75,35],[75,55],[75,75],[75,88]], [[75,55],[65,45],[52,42],[40,45],[32,55],[32,65],[40,75],[52,78],[65,75],[75,65]]],
  e: [[[22,52],[40,52],[58,52],[72,52],[72,45],[65,35],[52,28],[38,30],[25,40],[20,55],[22,68],[32,78],[45,82],[58,80],[68,72]]],
  f: [[[65,15],[55,10],[45,12],[38,22],[35,35],[35,55],[35,75],[35,88]], [[22,42],[35,42],[52,42]]],
  g: [[[68,35],[58,25],[45,25],[32,32],[25,45],[25,55],[32,68],[45,75],[58,75],[68,68],[68,55],[68,35],[68,55],[68,75],[68,88],[62,95],[50,98],[38,95],[30,88]]],
  h: [[[25,10],[25,35],[25,55],[25,75],[25,88]], [[25,52],[35,42],[48,38],[60,40],[68,50],[68,65],[68,75],[68,88]]],
  i: [[[50,28],[50,42],[50,55],[50,75],[50,88]], [[50,15],[50,18]]],
  j: [[[58,28],[58,42],[58,55],[58,75],[55,88],[48,95],[38,95],[30,88]], [[58,15],[58,18]]],
  k: [[[25,10],[25,35],[25,55],[25,75],[25,88]], [[65,35],[48,52],[25,55]], [[25,55],[45,65],[65,88]]],
  l: [[[50,10],[50,35],[50,55],[50,75],[50,88]]],
  m: [[[22,38],[22,55],[22,75],[22,88]], [[22,45],[32,35],[45,32],[55,35],[60,45],[60,55],[60,75],[60,88]], [[60,45],[70,35],[80,32],[88,35],[92,45],[92,55],[92,75],[92,88]]],
  n: [[[22,38],[22,55],[22,75],[22,88]], [[22,45],[32,35],[45,32],[58,35],[65,45],[65,55],[65,75],[65,88]]],
  o: [[[50,25],[62,28],[72,38],[75,50],[72,62],[62,72],[50,75],[38,72],[28,62],[25,50],[28,38],[38,28],[50,25]]],
  p: [[[25,38],[25,55],[25,75],[25,88],[25,100]], [[25,55],[35,45],[48,42],[60,45],[68,55],[68,65],[60,75],[48,78],[35,75],[25,65]]],
  q: [[[75,38],[75,55],[75,75],[75,88],[75,100]], [[75,55],[65,45],[52,42],[40,45],[32,55],[32,65],[40,75],[52,78],[65,75],[75,65]]],
  r: [[[25,38],[25,55],[25,75],[25,88]], [[25,48],[35,38],[48,35],[58,38]]],
  s: [[[68,35],[58,28],[45,28],[35,35],[30,45],[38,55],[52,58],[65,65],[68,75],[62,82],[50,85],[38,82],[28,75]]],
  t: [[[50,15],[50,35],[50,55],[50,75],[52,85],[58,90]], [[30,38],[50,38],[68,38]]],
  u: [[[25,35],[25,55],[25,70],[30,80],[40,88],[52,88],[62,82],[68,70],[68,55],[68,35],[68,55],[68,75],[68,88]]],
  v: [[[22,35],[38,62],[50,82],[62,62],[78,35]]],
  w: [[[18,35],[30,72],[42,52],[52,72],[62,52],[72,72],[82,35]]],
  x: [[[25,35],[42,52],[50,60],[62,72],[75,88]], [[75,35],[58,52],[50,60],[38,72],[25,88]]],
  y: [[[25,35],[38,58],[50,78]], [[75,35],[58,58],[50,78],[42,90],[32,95],[22,92]]],
  z: [[[22,35],[45,35],[68,35],[75,35]], [[75,35],[55,55],[50,62],[35,78],[22,88]], [[22,88],[45,88],[68,88],[75,88]]],
};

const HIT_RADIUS = 18; // px — how close the finger needs to be to a waypoint

// ─── Single guided canvas ─────────────────────────────────────────────────────

interface GuidedCanvasProps {
  letter: string;       // the letter to trace (upper or lower)
  isLower?: boolean;
  onComplete?: () => void;
}

function GuidedCanvas({ letter, isLower = false, onComplete }: GuidedCanvasProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const isDrawing = useRef(false);
  const [hitCount, setHitCount] = useState(0);
  const [complete, setComplete] = useState(false);
  const hitRef = useRef<Set<string>>(new Set()); // "strokeIdx-waypointIdx"

  const SIZE = 140;
  const paths = isLower
    ? (LOWER_PATHS[letter] ?? LETTER_PATHS[letter.toUpperCase()] ?? [])
    : (LETTER_PATHS[letter] ?? []);

  // Flatten all waypoints with their indices
  const allWaypoints = paths.flatMap((stroke, si) =>
    stroke.map((pt, wi) => ({ si, wi, x: (pt[0] / 100) * SIZE, y: (pt[1] / 100) * SIZE, key: `${si}-${wi}` }))
  );
  const totalWaypoints = allWaypoints.length;

  const drawGuide = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    ctx.clearRect(0, 0, SIZE, SIZE);

    // Ghost letter
    ctx.font = `bold ${SIZE * 0.72}px sans-serif`;
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.fillStyle = isLower ? "rgba(22,163,74,0.12)" : "rgba(245,158,11,0.12)";
    ctx.fillText(letter, SIZE / 2, SIZE / 2);

    // Draw waypoint dots
    allWaypoints.forEach(({ x, y, key }) => {
      const hit = hitRef.current.has(key);
      ctx.beginPath();
      ctx.arc(x, y, hit ? 5 : 4, 0, Math.PI * 2);
      ctx.fillStyle = hit
        ? "#22C55E"
        : isLower ? "rgba(22,163,74,0.35)" : "rgba(245,158,11,0.35)";
      ctx.fill();
    });

    // Draw path lines between waypoints (guide)
    paths.forEach(stroke => {
      if (stroke.length < 2) return;
      ctx.beginPath();
      ctx.moveTo((stroke[0][0] / 100) * SIZE, (stroke[0][1] / 100) * SIZE);
      stroke.slice(1).forEach(pt => ctx.lineTo((pt[0] / 100) * SIZE, (pt[1] / 100) * SIZE));
      ctx.strokeStyle = isLower ? "rgba(22,163,74,0.15)" : "rgba(245,158,11,0.15)";
      ctx.lineWidth = 8;
      ctx.lineCap = "round";
      ctx.lineJoin = "round";
      ctx.stroke();
    });
  }, [letter, isLower, allWaypoints, paths]);

  useEffect(() => {
    hitRef.current = new Set();
    setHitCount(0);
    setComplete(false);
    drawGuide();
  }, [letter, drawGuide]);

  function getPos(e: React.TouchEvent | React.MouseEvent): { x: number; y: number } {
    const canvas = canvasRef.current!;
    const rect = canvas.getBoundingClientRect();
    const scaleX = SIZE / rect.width;
    const scaleY = SIZE / rect.height;
    if ("touches" in e) {
      return {
        x: (e.touches[0].clientX - rect.left) * scaleX,
        y: (e.touches[0].clientY - rect.top) * scaleY,
      };
    }
    return {
      x: ((e as React.MouseEvent).clientX - rect.left) * scaleX,
      y: ((e as React.MouseEvent).clientY - rect.top) * scaleY,
    };
  }

  function checkWaypoints(x: number, y: number) {
    if (complete) return;
    let newHit = false;
    allWaypoints.forEach(({ x: wx, y: wy, key }) => {
      if (hitRef.current.has(key)) return;
      const dist = Math.sqrt((x - wx) ** 2 + (y - wy) ** 2);
      if (dist <= HIT_RADIUS) {
        hitRef.current.add(key);
        newHit = true;
      }
    });

    if (newHit) {
      const count = hitRef.current.size;
      setHitCount(count);
      drawGuide();

      // Complete when 75% of waypoints hit
      if (count / totalWaypoints >= 0.75 && !complete) {
        setComplete(true);
        onComplete?.();
      }
    }
  }

  function startDraw(e: React.TouchEvent | React.MouseEvent) {
    if (complete) return;
    isDrawing.current = true;
    const ctx = canvasRef.current?.getContext("2d");
    if (!ctx) return;
    const { x, y } = getPos(e);
    ctx.beginPath();
    ctx.moveTo(x, y);
    checkWaypoints(x, y);
  }

  function draw(e: React.TouchEvent | React.MouseEvent) {
    if (!isDrawing.current || complete) return;
    e.preventDefault();
    const ctx = canvasRef.current?.getContext("2d");
    if (!ctx) return;
    const { x, y } = getPos(e);
    ctx.lineTo(x, y);
    ctx.strokeStyle = isLower ? "#16A34A" : "#F59E0B";
    ctx.lineWidth = 8;
    ctx.lineCap = "round";
    ctx.lineJoin = "round";
    ctx.stroke();
    checkWaypoints(x, y);
  }

  function endDraw() {
    isDrawing.current = false;
  }

  function reset() {
    hitRef.current = new Set();
    setHitCount(0);
    setComplete(false);
    drawGuide();
  }

  const pct = totalWaypoints > 0 ? Math.round((hitCount / totalWaypoints) * 100) : 0;

  return (
    <div className="flex flex-col items-center gap-2">
      <span className="text-xs font-bold text-stone-500 uppercase tracking-wide">
        {isLower ? "Small" : "Capital"} {letter}
      </span>

      <div className="relative">
        <canvas
          ref={canvasRef}
          width={SIZE}
          height={SIZE}
          style={{ width: SIZE, height: SIZE }}
          className={`touch-none rounded-2xl border-2 bg-white transition-colors ${
            complete
              ? "border-green-400 shadow-md shadow-green-100"
              : "border-amber-200"
          }`}
          aria-label={`Trace the ${isLower ? "lowercase" : "uppercase"} letter ${letter}`}
          onMouseDown={startDraw}
          onMouseMove={draw}
          onMouseUp={endDraw}
          onMouseLeave={endDraw}
          onTouchStart={startDraw}
          onTouchMove={draw}
          onTouchEnd={endDraw}
        />

        {/* Completion overlay */}
        <AnimatePresence>
          {complete && (
            <motion.div
              initial={{ scale: 0, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              className="absolute inset-0 flex items-center justify-center rounded-2xl bg-green-500/20"
            >
              <motion.span
                initial={{ scale: 0 }}
                animate={{ scale: [0, 1.3, 1] }}
                transition={{ type: "spring", stiffness: 300 }}
                className="text-4xl"
              >
                ⭐
              </motion.span>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Progress bar */}
      <div className="w-full" style={{ width: SIZE }}>
        <div className="h-2 bg-stone-100 rounded-full overflow-hidden">
          <motion.div
            className={`h-full rounded-full ${complete ? "bg-green-500" : isLower ? "bg-green-400" : "bg-amber-400"}`}
            animate={{ width: `${pct}%` }}
            transition={{ duration: 0.2 }}
          />
        </div>
        <div className="flex justify-between mt-1">
          <span className="text-[10px] text-stone-400">
            {complete ? "✓ Perfect!" : `${pct}% traced`}
          </span>
          <button
            type="button"
            onClick={reset}
            className="text-[10px] text-stone-400 hover:text-stone-600 transition"
          >
            Reset
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── Main export ─────────────────────────────────────────────────────────────

interface TracingCanvasProps {
  letter: string;
  onTraced?: () => void;
}

export default function TracingCanvas({ letter, onTraced }: TracingCanvasProps) {
  const [upperDone, setUpperDone] = useState(false);
  const [lowerDone, setLowerDone] = useState(false);

  // Fire onTraced when both are complete
  const handleUpperDone = useCallback(() => {
    setUpperDone(true);
    if (lowerDone) onTraced?.();
  }, [lowerDone, onTraced]);

  const handleLowerDone = useCallback(() => {
    setLowerDone(true);
    if (upperDone) onTraced?.();
  }, [upperDone, onTraced]);

  const bothDone = upperDone && lowerDone;

  return (
    <div className="flex flex-col items-center gap-4 w-full">
      <p className="text-sm font-semibold text-stone-600 text-center">
        Follow the dots to trace the letter ✏️
      </p>

      <div className="flex gap-5 justify-center flex-wrap">
        <GuidedCanvas
          letter={letter.toUpperCase()}
          isLower={false}
          onComplete={handleUpperDone}
        />
        <GuidedCanvas
          letter={letter.toLowerCase()}
          isLower={true}
          onComplete={handleLowerDone}
        />
      </div>

      <AnimatePresence>
        {bothDone && (
          <motion.div
            initial={{ scale: 0.8, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="bg-green-50 border-2 border-green-300 rounded-2xl px-5 py-3 text-center"
          >
            <p className="font-extrabold text-green-700">🎉 Amazing tracing!</p>
            <p className="text-green-600 text-xs mt-0.5">You traced both letters perfectly!</p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
