/**
 * Letter data — word associations, phonetics, and illustration URLs.
 * Images use OpenMoji (https://openmoji.org) — free, open-source emoji illustrations.
 * OpenMoji CDN: https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/{unicode}.svg
 *
 * LANGUAGES:
 * - English: 26 letters (A–Z)
 * - Yorùbá: 25 letters (A B D E Ẹ F G GB H I J K L M N O Ọ P R S Ṣ T U W Y)
 * - French: 26 letters (A–Z with African words)
 * - Igbo: 26 letters (coming soon)
 * - Hausa: 26 letters (coming soon)
 */
import type { LetterConfig } from "@/types";

// ─── ENGLISH LETTERS (26) ────────────────────────────────────────────────────

export const ENGLISH_LETTERS: Record<string, LetterConfig> = {
  A: {
    letter: "A",
    displayLetter: "A",
    phonetic: "ay",
    englishWord: "Apple",
    localWord: "Àgbàdo",
    localWordMeaning: "corn",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F34E.svg",
  },
  B: {
    letter: "B",
    displayLetter: "B",
    phonetic: "bee",
    englishWord: "Ball",
    localWord: "Bàtà",
    localWordMeaning: "drum",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/26BD.svg",
  },
  C: {
    letter: "C",
    displayLetter: "C",
    phonetic: "see",
    englishWord: "Cat",
    localWord: "Ẹkùn",
    localWordMeaning: "leopard",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F431.svg",
  },
  D: {
    letter: "D",
    displayLetter: "D",
    phonetic: "dee",
    englishWord: "Dog",
    localWord: "Ẹja",
    localWordMeaning: "fish",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F436.svg",
  },
  E: {
    letter: "E",
    displayLetter: "E",
    phonetic: "ee",
    englishWord: "Egg",
    localWord: "Ẹyin",
    localWordMeaning: "egg",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F95A.svg",
  },
  F: {
    letter: "F",
    displayLetter: "F",
    phonetic: "ef",
    englishWord: "Fish",
    localWord: "Ẹja",
    localWordMeaning: "fish",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F41F.svg",
  },
  G: {
    letter: "G",
    displayLetter: "G",
    phonetic: "jee",
    englishWord: "Goat",
    localWord: "Ewúrẹ",
    localWordMeaning: "goat",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F410.svg",
  },
  H: {
    letter: "H",
    displayLetter: "H",
    phonetic: "aych",
    englishWord: "House",
    localWord: "Ilé",
    localWordMeaning: "house",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F3E0.svg",
  },
  I: {
    letter: "I",
    displayLetter: "I",
    phonetic: "eye",
    englishWord: "Ice cream",
    localWord: "Isu",
    localWordMeaning: "yam",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F368.svg",
  },
  J: {
    letter: "J",
    displayLetter: "J",
    phonetic: "jay",
    englishWord: "Jug",
    localWord: "Jẹ",
    localWordMeaning: "eat",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1FAD9.svg",
  },
  K: {
    letter: "K",
    displayLetter: "K",
    phonetic: "kay",
    englishWord: "Kite",
    localWord: "Kòkò",
    localWordMeaning: "parrot",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1FA81.svg",
  },
  L: {
    letter: "L",
    displayLetter: "L",
    phonetic: "el",
    englishWord: "Lion",
    localWord: "Ẹkùn",
    localWordMeaning: "lion",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F981.svg",
  },
  M: {
    letter: "M",
    displayLetter: "M",
    phonetic: "em",
    englishWord: "Mango",
    localWord: "Màngoro",
    localWordMeaning: "mango",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F96D.svg",
  },
  N: {
    letter: "N",
    displayLetter: "N",
    phonetic: "en",
    englishWord: "Nose",
    localWord: "Imú",
    localWordMeaning: "nose",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F443.svg",
  },
  O: {
    letter: "O",
    displayLetter: "O",
    phonetic: "oh",
    englishWord: "Orange",
    localWord: "Ọsàn",
    localWordMeaning: "orange",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F34A.svg",
  },
  P: {
    letter: "P",
    displayLetter: "P",
    phonetic: "pee",
    englishWord: "Parrot",
    localWord: "Ọ̀pẹ",
    localWordMeaning: "palm tree",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F99C.svg",
  },
  Q: {
    letter: "Q",
    displayLetter: "Q",
    phonetic: "kyoo",
    englishWord: "Queen",
    localWord: "Ayaba",
    localWordMeaning: "queen",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F451.svg",
  },
  R: {
    letter: "R",
    displayLetter: "R",
    phonetic: "ar",
    englishWord: "Rain",
    localWord: "Òjò",
    localWordMeaning: "rain",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F327.svg",
  },
  S: {
    letter: "S",
    displayLetter: "S",
    phonetic: "es",
    englishWord: "Sun",
    localWord: "Òòrùn",
    localWordMeaning: "sun",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/2600.svg",
  },
  T: {
    letter: "T",
    displayLetter: "T",
    phonetic: "tee",
    englishWord: "Tree",
    localWord: "Igi",
    localWordMeaning: "tree",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F333.svg",
  },
  U: {
    letter: "U",
    displayLetter: "U",
    phonetic: "yoo",
    englishWord: "Umbrella",
    localWord: "Agboorun",
    localWordMeaning: "umbrella",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/2602.svg",
  },
  V: {
    letter: "V",
    displayLetter: "V",
    phonetic: "vee",
    englishWord: "Village",
    localWord: "Abúlé",
    localWordMeaning: "village",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F3D8.svg",
  },
  W: {
    letter: "W",
    displayLetter: "W",
    phonetic: "double-yoo",
    englishWord: "Water",
    localWord: "Omi",
    localWordMeaning: "water",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F4A7.svg",
  },
  X: {
    letter: "X",
    displayLetter: "X",
    phonetic: "ex",
    englishWord: "Xylophone",
    localWord: "Gángan",
    localWordMeaning: "talking drum",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F941.svg",
  },
  Y: {
    letter: "Y",
    displayLetter: "Y",
    phonetic: "why",
    englishWord: "Yam",
    localWord: "Isu",
    localWordMeaning: "yam",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F360.svg",
  },
  Z: {
    letter: "Z",
    displayLetter: "Z",
    phonetic: "zee",
    englishWord: "Zebra",
    localWord: "Kẹ́tẹ́kẹ́tẹ́",
    localWordMeaning: "donkey",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F993.svg",
  },
};

// ─── YORÙBÁ LETTERS (25) ─────────────────────────────────────────────────────
// Yorùbá alphabet: A B D E Ẹ F G GB H I J K L M N O Ọ P R S Ṣ T U W Y
// Note: C, Q, V, X, Z do not exist in Yorùbá
// Special letters: Ẹ (e with dot below), Ọ (o with dot below), Ṣ (s with dot below)
// GB is a digraph (two letters making one sound)

export const YORUBA_LETTERS: Record<string, LetterConfig> = {
  A: {
    letter: "A",
    displayLetter: "A",
    phonetic: "ah",
    englishWord: "Corn",
    localWord: "Àgbàdo",
    localWordMeaning: "Corn",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F33D.svg",
  },
  B: {
    letter: "B",
    displayLetter: "B",
    phonetic: "beh",
    englishWord: "Drum",
    localWord: "Bàtà",
    localWordMeaning: "Drum",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F941.svg",
  },
  D: {
    letter: "D",
    displayLetter: "D",
    phonetic: "deh",
    englishWord: "Fried Plantain",
    localWord: "Dodo",
    localWordMeaning: "Fried plantain",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F35E.svg",
  },
  E: {
    letter: "E",
    displayLetter: "E",
    phonetic: "eh",
    englishWord: "Egg",
    localWord: "Ẹyin",
    localWordMeaning: "Egg",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F95A.svg",
  },
  "Ẹ": {
    letter: "Ẹ",
    displayLetter: "Ẹ/ẹ",
    phonetic: "ẹh",
    englishWord: "Corn pudding",
    localWord: "Ẹkọ",
    localWordMeaning: "Corn pudding",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F35F.svg",
    hasSubscript: true,
  },
  F: {
    letter: "F",
    displayLetter: "F",
    phonetic: "feh",
    englishWord: "Cap",
    localWord: "Fìlà",
    localWordMeaning: "Cap",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F9E2.svg",
  },
  G: {
    letter: "G",
    displayLetter: "G",
    phonetic: "geh",
    englishWord: "Bucket",
    localWord: "Garawa",
    localWordMeaning: "Bucket",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F4EB.svg",
  },
  GB: {
    letter: "GB",
    displayLetter: "GB/gb",
    phonetic: "gb",
    englishWord: "Enjoyment",
    localWord: "Gbàdùn",
    localWordMeaning: "Enjoyment",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F60A.svg",
    isDigraph: true,
  },
  H: {
    letter: "H",
    displayLetter: "H",
    phonetic: "heh",
    englishWord: "House",
    localWord: "Ilé",
    localWordMeaning: "House",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F3E0.svg",
  },
  I: {
    letter: "I",
    displayLetter: "I",
    phonetic: "ee",
    englishWord: "Pounded Yam",
    localWord: "Ìyán",
    localWordMeaning: "Pounded yam",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F360.svg",
  },
  J: {
    letter: "J",
    displayLetter: "J",
    phonetic: "jeh",
    englishWord: "Food",
    localWord: "Jẹun",
    localWordMeaning: "Food",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F32E.svg",
  },
  K: {
    letter: "K",
    displayLetter: "K",
    phonetic: "keh",
    englishWord: "Parrot",
    localWord: "Kòkò",
    localWordMeaning: "Parrot",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F99C.svg",
  },
  L: {
    letter: "L",
    displayLetter: "L",
    phonetic: "leh",
    englishWord: "Fabric",
    localWord: "Làpá",
    localWordMeaning: "Fabric",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F9F0.svg",
  },
  M: {
    letter: "M",
    displayLetter: "M",
    phonetic: "meh",
    englishWord: "Mother",
    localWord: "Màmá",
    localWordMeaning: "Mother",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F469.svg",
  },
  N: {
    letter: "N",
    displayLetter: "N",
    phonetic: "neh",
    englishWord: "Something",
    localWord: "Nǹkan",
    localWordMeaning: "Something",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F4A1.svg",
  },
  O: {
    letter: "O",
    displayLetter: "O",
    phonetic: "oh",
    englishWord: "Water",
    localWord: "Omi",
    localWordMeaning: "Water",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F4A7.svg",
  },
  "Ọ": {
    letter: "Ọ",
    displayLetter: "Ọ/ọ",
    phonetic: "ọh",
    englishWord: "Farm tool",
    localWord: "Ọkọ",
    localWordMeaning: "Farm tool",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F6E0.svg",
    hasSubscript: true,
  },
  P: {
    letter: "P",
    displayLetter: "P",
    phonetic: "peh",
    englishWord: "Important",
    localWord: "Pàtàkì",
    localWordMeaning: "Important",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F31F.svg",
  },
  R: {
    letter: "R",
    displayLetter: "R",
    phonetic: "reh",
    englishWord: "Help",
    localWord: "Ràn",
    localWordMeaning: "To help",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F91D.svg",
  },
  S: {
    letter: "S",
    displayLetter: "S",
    phonetic: "seh",
    englishWord: "Sleep",
    localWord: "Sùn",
    localWordMeaning: "To sleep",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F6CF.svg",
  },
  "Ṣ": {
    letter: "Ṣ",
    displayLetter: "Ṣ/ṣ",
    phonetic: "sh",
    englishWord: "Work",
    localWord: "Ṣíṣe",
    localWordMeaning: "Work",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F4BC.svg",
    hasSubscript: true,
  },
  T: {
    letter: "T",
    displayLetter: "T",
    phonetic: "teh",
    englishWord: "That",
    localWord: "Tí",
    localWordMeaning: "That",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F0CF.svg",
  },
  U: {
    letter: "U",
    displayLetter: "U",
    phonetic: "oo",
    englishWord: "Dove",
    localWord: "Ùgbẹ́lẹ̀",
    localWordMeaning: "Dove",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F54A.svg",
  },
  W: {
    letter: "W",
    displayLetter: "W",
    phonetic: "weh",
    englishWord: "Milk",
    localWord: "Wàrà",
    localWordMeaning: "Milk",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F95B.svg",
  },
  Y: {
    letter: "Y",
    displayLetter: "Y",
    phonetic: "yeh",
    englishWord: "Sand",
    localWord: "Yànrìn",
    localWordMeaning: "Sand",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F3D6.svg",
  },
};

// ─── FRENCH LETTERS (26) ──────────────────────────────────────────────────────
// Standard A–Z with African-themed words

export const FRENCH_LETTERS: Record<string, LetterConfig> = {
  A: {
    letter: "A",
    displayLetter: "A",
    phonetic: "ah",
    englishWord: "Pineapple",
    localWord: "Ananas",
    localWordMeaning: "Pineapple",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F34D.svg",
  },
  B: {
    letter: "B",
    displayLetter: "B",
    phonetic: "beh",
    englishWord: "Baobab tree",
    localWord: "Baobab",
    localWordMeaning: "Baobab tree",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F333.svg",
  },
  C: {
    letter: "C",
    displayLetter: "C",
    phonetic: "seh",
    englishWord: "Crocodile",
    localWord: "Caïman",
    localWordMeaning: "Crocodile",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F40E.svg",
  },
  D: {
    letter: "D",
    displayLetter: "D",
    phonetic: "deh",
    englishWord: "Dakar",
    localWord: "Dakar",
    localWordMeaning: "City in Senegal",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F3D9.svg",
  },
  E: {
    letter: "E",
    displayLetter: "E",
    phonetic: "uh",
    englishWord: "Elephant",
    localWord: "Éléphant",
    localWordMeaning: "Elephant",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F418.svg",
  },
  F: {
    letter: "F",
    displayLetter: "F",
    phonetic: "eff",
    englishWord: "River",
    localWord: "Fleuve",
    localWordMeaning: "River",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F3DE.svg",
  },
  G: {
    letter: "G",
    displayLetter: "G",
    phonetic: "zheh",
    englishWord: "Giraffe",
    localWord: "Girafe",
    localWordMeaning: "Giraffe",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F992.svg",
  },
  H: {
    letter: "H",
    displayLetter: "H",
    phonetic: "ash",
    englishWord: "Hippo",
    localWord: "Hippopotame",
    localWordMeaning: "Hippo",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F99B.svg",
  },
  I: {
    letter: "I",
    displayLetter: "I",
    phonetic: "ee",
    englishWord: "Yam",
    localWord: "Igname",
    localWordMeaning: "Yam",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F360.svg",
  },
  J: {
    letter: "J",
    displayLetter: "J",
    phonetic: "zhee",
    englishWord: "Jungle",
    localWord: "Jungle",
    localWordMeaning: "Jungle",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F32B.svg",
  },
  K: {
    letter: "K",
    displayLetter: "K",
    phonetic: "kah",
    englishWord: "Kola nut",
    localWord: "Kola",
    localWordMeaning: "Kola nut",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F95C.svg",
  },
  L: {
    letter: "L",
    displayLetter: "L",
    phonetic: "ell",
    englishWord: "Lion",
    localWord: "Lion",
    localWordMeaning: "Lion",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F981.svg",
  },
  M: {
    letter: "M",
    displayLetter: "M",
    phonetic: "em",
    englishWord: "Mango tree",
    localWord: "Manguier",
    localWordMeaning: "Mango tree",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F96D.svg",
  },
  N: {
    letter: "N",
    displayLetter: "N",
    phonetic: "en",
    englishWord: "Coconut",
    localWord: "Noix de coco",
    localWordMeaning: "Coconut",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F25F.svg",
  },
  O: {
    letter: "O",
    displayLetter: "O",
    phonetic: "oh",
    englishWord: "Orange",
    localWord: "Orange",
    localWordMeaning: "Orange",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F34A.svg",
  },
  P: {
    letter: "P",
    displayLetter: "P",
    phonetic: "peh",
    englishWord: "Palm tree",
    localWord: "Palmier",
    localWordMeaning: "Palm tree",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F334.svg",
  },
  Q: {
    letter: "Q",
    displayLetter: "Q",
    phonetic: "kew",
    englishWord: "Tail",
    localWord: "Queue",
    localWordMeaning: "Tail",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F43E.svg",
  },
  R: {
    letter: "R",
    displayLetter: "R",
    phonetic: "err",
    englishWord: "River",
    localWord: "Rivière",
    localWordMeaning: "River",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F3DE.svg",
  },
  S: {
    letter: "S",
    displayLetter: "S",
    phonetic: "ess",
    englishWord: "Savanna",
    localWord: "Savane",
    localWordMeaning: "Savanna",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F3DD.svg",
  },
  T: {
    letter: "T",
    displayLetter: "T",
    phonetic: "teh",
    englishWord: "Drum",
    localWord: "Tambour",
    localWordMeaning: "Drum",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F941.svg",
  },
  U: {
    letter: "U",
    displayLetter: "U",
    phonetic: "ew",
    englishWord: "Unity",
    localWord: "Unité",
    localWordMeaning: "Unity",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F91D.svg",
  },
  V: {
    letter: "V",
    displayLetter: "V",
    phonetic: "veh",
    englishWord: "Village",
    localWord: "Village",
    localWordMeaning: "Village",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F3D8.svg",
  },
  W: {
    letter: "W",
    displayLetter: "W",
    phonetic: "doo-bluh-veh",
    englishWord: "Warthog",
    localWord: "Warthog",
    localWordMeaning: "Warthog",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F417.svg",
  },
  X: {
    letter: "X",
    displayLetter: "X",
    phonetic: "eeks",
    englishWord: "Xylophone",
    localWord: "Xylophone",
    localWordMeaning: "Xylophone",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F941.svg",
  },
  Y: {
    letter: "Y",
    displayLetter: "Y",
    phonetic: "ee-greck",
    englishWord: "Yam",
    localWord: "Yam",
    localWordMeaning: "Yam",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F360.svg",
  },
  Z: {
    letter: "Z",
    displayLetter: "Z",
    phonetic: "zed",
    englishWord: "Zebra",
    localWord: "Zèbre",
    localWordMeaning: "Zebra",
    imageUrl: "https://cdn.jsdelivr.net/npm/openmoji@15.0.0/color/svg/1F993.svg",
  },
};

// ─── LETTER DATA MAP ─────────────────────────────────────────────────────────
// Maps language to its letter set

export const LETTER_DATA: Record<string, Record<string, LetterConfig>> = {
  english: ENGLISH_LETTERS,
  yoruba: YORUBA_LETTERS,
  french: FRENCH_LETTERS,
};

export function getClipUrl(language: string, letter: string): string | null {
  return `/audio/${language}/${letter.toLowerCase()}.mp3`;
}
